package tf.bug.alymod.monk;

public enum CooldownGroup {
    GCD,
    INTERNAL_RELEASE,
    FISTS,
    TACKLES,
    STEEL_PEAK,
    MANTRA,
    HOWLING_FIST,
    PERFECT_BALANCE,
    THE_FORBIDDEN_CHAKRA,
    ELIXIR_FIELD,
    TORNADO_KICK,
    RIDDLE_OF_EARTH,
    RIDDLE_OF_WIND,
    RIDDLE_OF_FIRE,
    BROTHERHOOD,
    SECOND_WIND,
}
